version: "2"

formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt

linters:
  default: none
  enable:
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - staticcheck
    - unconvert
    - gocritic
    - durationcheck
  settings:
    misspell:
      locale: US
    goheader:
      values:
        regexp:
          copyright-holder: Copyright \(c\) (20\d\d\-20\d\d)|2021|({{year}})
      template-path: .license.tmpl
  exclusions:
    rules:
      - text: "should have a package comment"
        linters: [revive]
      - text: "comment on exported function"
        linters: [revive]
      - text: "comment on exported type"
        linters: [revive]
      - text: "should have comment"
        linters: [revive]
      - text: "use leading k in Go names"
        linters: [revive]
      - text: "comment on exported const"
        linters: [revive]
    paths:
      - api/operations
