version: "2"

linters-settings:
  misspell:
    locale: US

  goheader:
    values:
      regexp:
        copyright-holder: Copyright \(c\) (20\d\d\-20\d\d)|2021|({{year}})
    template-path: .license.tmpl

formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt

linters:
  disable-all: true
  enable:
    - misspell
    - govet
    - revive
    - ineffassign
    - gomodguard
    - staticcheck
    - unconvert
    - gocritic
    - durationcheck

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    # TODO(y4m4): Remove once all exported ident. have comments!
    - comment on exported function
    - comment on exported type
    - should have comment
    - use leading k in Go names
    - comment on exported const
  exclude-dirs:
    - api/operations
